# Generated by Django 6.0 on 2026-02-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['created_at']},
        ),
    ]
