# Generated by Django 5.2 on 2025-06-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_destination_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('transport', 'Transportation'), ('food', 'Food & Dining'), ('activities', 'Activities & Tours'), ('shopping', 'Shopping'), ('misc', 'Miscellaneous')], max_length=20)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_components', to='content.destination')),
            ],
        ),
    ]
