# Generated by Django 5.2 on 2025-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcomponent',
            name='category',
            field=models.CharField(choices=[('camping', 'Camping & Accommodation'), ('transport', 'Transportation'), ('food', 'Food & Dining'), ('activities', 'Activities & Tours'), ('shopping', 'Shopping'), ('misc', 'Miscellaneous')], max_length=20),
        ),
    ]
