# Generated by Django 5.1.13 on 2025-12-14 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_company_tourpackage_packageimage_packagereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packageimage",
            options={"ordering": ["-is_primary", "-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="company",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="license_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tour_packages",
                to="content.destination",
            ),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="destinations_covered",
            field=models.TextField(help_text="Comma-separated list of destinations"),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="duration_days",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="duration_nights",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="exclusions",
            field=models.TextField(help_text="What is not included"),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="packages/"),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="inclusions",
            field=models.TextField(help_text="What is included in the package"),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="max_people",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="min_people",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="Special requirements or conditions"
            ),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="packagereview",
            unique_together={("package", "user")},
        ),
    ]
