# Generated by Django 5.1.13 on 2026-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_remove_tourpackage_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Weight in kilograms",
                max_digits=5,
            ),
        ),
    ]
