# Generated by Django 5.2.9 on 2026-02-15 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_product_weight_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed by Admin'), ('approved', 'Approved'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('num_days', models.PositiveIntegerField()),
                ('num_people', models.PositiveIntegerField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('vehicle', models.CharField(choices=[('grand-cabin', 'Grand Cabin (7-13 people)'), ('coaster', 'Coaster (14-27 people)')], max_length=20)),
                ('food', models.CharField(choices=[('both', 'Breakfast & Dinner'), ('breakfast', 'Breakfast Only'), ('dinner', 'Dinner Only'), ('none', 'No Food')], max_length=20)),
                ('accommodation', models.CharField(choices=[('luxury', 'Luxury'), ('delux', 'Delux'), ('standard', 'Standard')], max_length=20)),
                ('guide', models.BooleanField(default=False)),
                ('bonfire', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('per_person_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_package_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('custom_package', 'New Custom Package Request'), ('payment', 'Payment Received'), ('order', 'New Product Order'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_package_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='content.custompackageorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
