# Generated by Django 6.0 on 2026-02-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_product_company_product_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='custompackageorder',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at']},
        ),
    ]
