# Generated by Django 5.1.13 on 2025-12-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_company_approval_status_company_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
