# Generated by Django 5.2.9 on 2026-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_company_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnic_back',
            field=models.ImageField(blank=True, help_text='Back side of CNIC', null=True, upload_to='companies/cnic/'),
        ),
        migrations.AddField(
            model_name='company',
            name='cnic_front',
            field=models.ImageField(blank=True, help_text='Front side of CNIC', null=True, upload_to='companies/cnic/'),
        ),
    ]
