# Generated by Django 5.2.9 on 2026-02-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_company_cnic_back_company_cnic_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='companies/cnic/', verbose_name='CNIC Back'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='companies/cnic/', verbose_name='CNIC Front'),
        ),
    ]
