# Generated by Django 5.2.9 on 2026-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_company_cnic_back_alter_company_cnic_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='inclusions',
            field=models.TextField(blank=True, default='', help_text="What's included in the package (one item per line)"),
        ),
    ]
