# Generated by Django 5.2.9 on 2026-02-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_packagereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
