# Generated by Django 6.0 on 2026-02-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['created_at']},
        ),
    ]
